name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${GITHUB_REF##*/}
      - name: Login Github Package
        run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USER}}/flutter-demo1:latest .
      - name: Push the Docker image
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/flutter-demo1:latest
