name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Github Package
        run: docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USER}}/${{github.event.repository.name}}:${GITHUB_REF##*/} .
      - name: Push the Docker image
        run: docker push ${{secrets.DOCKERHUB_USER}}/${{github.event.repository.name}}:${GITHUB_REF##*/}
