name: Docker Image CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Github Package
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:${GITHUB_REF##*/} .
          docker tag ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:${GITHUB_REF##*/} ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}
          docker push ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:${GITHUB_REF##*/}
          docker push ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}
